/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author amelia
 */
public class info extends javax.swing.JPanel {

    /**
     * Creates new form info
     */
    public info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infonih = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        infonih.setBackground(new java.awt.Color(204, 204, 255));
        infonih.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 36)); // NOI18N
        jLabel1.setText("OUR TEAM");
        infonih.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 36)); // NOI18N
        jLabel6.setText("OBJEK");
        infonih.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 14)); // NOI18N
        jLabel7.setText("SHAFIRA");
        infonih.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Black Cat.png"))); // NOI18N
        infonih.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 24)); // NOI18N
        jLabel10.setText("PEMROGRAMAN BERORIENTASI");
        infonih.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 14)); // NOI18N
        jLabel8.setText("422021618067");
        infonih.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 14)); // NOI18N
        jLabel9.setText("AMELIA FITRI 'AINI");
        infonih.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 14)); // NOI18N
        jLabel11.setText("422021618067");
        infonih.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        add(infonih, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel infonih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
